### ISSUE TITLE
[socialsphere app] NullPointerException when populating SDG Graph with RTA Wala Algorithm.

### ISSUE THREAD

**Issue by fabio-franco** [konveyor/dgi-code-analyzer#13]
When using the socialsphere app (https://ibm.box.com/s/hmoyrj77t5eub7i9x437ckqymvxeqncj) in the binary analyzer, we can see a NullPointerException when the code starts to populate the graph inside the `buildGraph` method in `SDGGraph2JSON`.

```
entered in buildGraph method 
Time (in milliseconds) to populate dfsFinish and dfsStart in buildGraph method: 89146
[SEVERE ] Problem to generate callGraph-method: java.lang.NullPointerException
[SEVERE ] Problem to generate callGraph-method message: null
[SEVERE ] Problem to generate callGraph-method cause: null
java.lang.NullPointerException
	at com.ibm.minerva.dgi.utils.SDGGraph2JSON.lambda$null$1(SDGGraph2JSON.java:130)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at com.ibm.minerva.dgi.utils.SDGGraph2JSON.lambda$buildGraph$2(SDGGraph2JSON.java:127)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.ibm.minerva.dgi.utils.SDGGraph2JSON.buildGraph(SDGGraph2JSON.java:127)
	at com.ibm.minerva.dgi.utils.SDGGraph2JSON.convertAndSave(SDGGraph2JSON.java:262)
	at com.ibm.minerva.analyzer.CallGraphBuilder.write(CallGraphBuilder.java:295)
	at com.ibm.minerva.analyzer.TableBuilder.writeCallGraphs(TableBuilder.java:212)
	at com.ibm.minerva.analyzer.TableBuilder.write(TableBuilder.java:180)
	at com.ibm.minerva.analyzer.Analyzer.run(Analyzer.java:180)
	at com.ibm.mono2micro.cli.subcommands.BinaryAnalyzer.executeAnalyzer(BinaryAnalyzer.java:193)
	at com.ibm.mono2micro.cli.subcommands.AnalyzeAsClass.run(AnalyzeAsClass.java:126)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.ibm.mono2micro.cli.Mono2MicroCommand.main(Mono2MicroCommand.java:121)
```
To get this error, I haven't used any additional library and I haven't excluded any package to run it.

Having said that, I fixed this issue when using the WALA 01CFA algorithm by verifying if the dfsStart contains p and s before trying to access their nodes:

```
sdg.stream()
                .filter(dfsFinish::containsKey)
                .sorted(Comparator.comparingInt(dfsFinish::get))
                .forEach(p -> sdg.getSuccNodes(p).forEachRemaining(s -> {
                    if (dfsFinish.containsKey(s)
                    	   && dfsStart.get(p) != null && dfsStart.get(s) != null
                            && !((dfsStart.get(p) >= dfsStart.get(s))
                            && (dfsFinish.get(p) <= dfsFinish.get(s)))
                            && !p.getNode().getMethod().equals(s.getNode().getMethod())) {
...
                    }
```

However, this fix works fine just when using 01CFA algorithm. When using WALA RTA with the fix above, I can see this other issue:
```
entered in buildGraph method 
[SEVERE ] Problem to generate callGraph-method: java.lang.NullPointerException
[SEVERE ] Problem to generate callGraph-method message: null
[SEVERE ] Problem to generate callGraph-method cause: null
java.lang.NullPointerException
	at com.ibm.wala.ipa.slicer.SDG$Edges.getSuccNodes(SDG.java:522)
	at com.ibm.wala.ipa.slicer.SDG$Edges.getSuccNodes(SDG.java:273)
	at com.ibm.wala.util.graph.AbstractGraph.getSuccNodes(AbstractGraph.java:76)
	at com.ibm.wala.util.graph.GraphSlicer$2.getSuccNodes(GraphSlicer.java:116)
	at com.ibm.wala.util.graph.AbstractGraph.getSuccNodes(AbstractGraph.java:76)
	at com.ibm.wala.util.graph.traverse.DFSFinishTimeIterator.getConnected(DFSFinishTimeIterator.java:129)
	at com.ibm.wala.util.graph.traverse.DFSFinishTimeIterator.next(DFSFinishTimeIterator.java:104)
	at com.ibm.minerva.dgi.utils.SDGGraph2JSON.buildGraph(SDGGraph2JSON.java:95)
	at com.ibm.minerva.dgi.utils.SDGGraph2JSON.convertAndSave(SDGGraph2JSON.java:263)
	at com.ibm.minerva.analyzer.CallGraphBuilder.write(CallGraphBuilder.java:295)
	at com.ibm.minerva.analyzer.TableBuilder.writeCallGraphs(TableBuilder.java:212)
	at com.ibm.minerva.analyzer.TableBuilder.write(TableBuilder.java:180)
	at com.ibm.minerva.analyzer.Analyzer.run(Analyzer.java:180)
	at com.ibm.mono2micro.cli.subcommands.BinaryAnalyzer.executeAnalyzer(BinaryAnalyzer.java:193)
	at com.ibm.mono2micro.cli.subcommands.AnalyzeAsClass.run(AnalyzeAsClass.java:126)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.ibm.mono2micro.cli.Mono2MicroCommand.main(Mono2MicroCommand.java:121)
```

Any thoughts?

**Comment by fabio-franco** [comment]
Fixed by https://github.com/konveyor/dgi-code-analyzer/issues/14
