### ISSUE TITLE
Process fail when the binary has a class without package name

### ISSUE THREAD

**Issue by fabio-franco** [konveyor/dgi-code-analyzer#8]
That was the issue when running the code analyzer using defaultapp (https://github.com/kpostreich/m2m-ws-sample/tree/master/defaultapplication/monolith), which has HitCount as a class without a package name:

```
[36m2023-08-16T13:11:02.493636[0m[35m	[INFO]	[0mCreate analysis scope.
[36m2023-08-16T13:11:02.589434[0m[35m	[INFO]	[0mAdd exclusions to scope.
[36m2023-08-16T13:11:02.590913[0m[35m	[INFO]	[0mLoading Java SE standard libs.
[36m2023-08-16T13:11:02.631317[0m[33m	[WARN]	[0mNo extra libraries to process.
[36m2023-08-16T13:11:02.641869[0m[35m	[INFO]	[0mLoading application jar(s).
[36m2023-08-16T13:11:02.667835[0m[35m	[INFO]	[0m-> Adding application DefaultApplication.ear to analysis scope.
[36m2023-08-16T13:11:02.668173[0m[35m	[INFO]	[0mMake class hierarchy.
[36m2023-08-16T13:11:04.800612[0m[32m	[DONE]	[0mThere were a total of 27015 classes of which 0 are application classes.
[36m2023-08-16T13:11:04.821697[0m[35m	[INFO]	[0mRegistered 0 entrypoints.
[36m2023-08-16T13:11:04.836336[0m[35m	[INFO]	[0mBuilding call graph.
java.lang.IllegalStateException: Could not create a entrypoint callsites: 1. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/HitCount
2. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/SnoopServlet
3. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/defaultapplication/Increment
4. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/defaultapplication/IncrementAction
5. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/defaultapplication/IncrementSSB
6. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/BasicImageReader
7. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/BasicImageReader$1
8. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/BasicImageReader$2
9. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageBufferCache
10. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageBufferCache$1
11. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageBufferCache$2
12. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageBufferCache$BufferReference
13. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageHeader
14. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageLocation
15. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader
16. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$Directory
17. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$LinkNode
18. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$Node
19. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$Resource
20. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$SharedImageReader
21. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$SharedImageReader$LocationVisitor
22. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReaderFactory
23. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReaderFactory$1
24. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageStream
25. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageStrings
26. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageStringsReader
27. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/NativeImageBuffer
28. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/NativeImageBuffer$1
29. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/CompressIndexes
30. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/CompressedResourceHeader
31. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/Decompressor
32. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ResourceDecompressor
33. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ResourceDecompressor$StringsProvider
34. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ResourceDecompressorFactory
35. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ResourceDecompressorRepository
36. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/SignatureParser
37. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/SignatureParser$ParseResult
38. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/StringSharingDecompressor
39. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/StringSharingDecompressorFactory
40. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ZipDecompressor
41. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ZipDecompressorFactory
42. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/ExplodedImage
43. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/ExplodedImage$PathNode
44. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtDirectoryStream
45. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtDirectoryStream$1
46. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileAttributeView
47. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileAttributeView$1
48. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileAttributeView$AttrID
49. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileAttributes
50. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileStore
51. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystem
52. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystem$1
53. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystemProvider
54. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystemProvider$1
55. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystemProvider$JrtFsLoader
56. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtPath
57. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtPath$1
58. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtPath$2
59. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtUtils
60. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/SystemImage
61. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/SystemImage$1
62. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/SystemImage$2

	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:238)
	at org.konveyor.dgi.CodeAnalyzer.run(CodeAnalyzer.java:134)
	at org.konveyor.dgi.CodeAnalyzer.main(CodeAnalyzer.java:94)
```

**Comment by fabio-franco** [comment]
Fixed by https://github.com/konveyor/dgi-code-analyzer/issues/14
