### ISSUE TITLE
[plantsbywebsphere] Fail when running ./codeanalyzer 

### ISSUE THREAD

**Issue by fabio-franco** [konveyor/dgi-code-analyzer#9]
This issue was captured when running `plantsbywebsphere`
[plants.zip](https://github.com/konveyor/dgi-code-analyzer/files/12362169/plants.zip)

Just rename the file above from .zip to .war

```
./codeanalyzer -i /Users/fabiofranco/Downloads/cargo-tests/apps/plants/without-libs/binary -o /Users/fabiofranco/Downloads/cargo-tests/apps/plants/without-libs/input
2023-08-16T13:49:40.184718        [INFO]  Create analysis scope.
2023-08-16T13:49:40.251334        [INFO]  Add exclusions to scope.
2023-08-16T13:49:40.252255        [INFO]  Loading Java SE standard libs.
2023-08-16T13:49:40.294103        [WARN]  No extra libraries to process.
2023-08-16T13:49:40.308216        [INFO]  Loading application jar(s).
2023-08-16T13:49:40.313122        [INFO]  -> Adding application plants.war to analysis scope.
2023-08-16T13:49:40.314781        [INFO]  Make class hierarchy.
2023-08-16T13:49:42.469541        [DONE]  There were a total of 27015 classes of which 0 are application classes.
2023-08-16T13:49:42.488646        [INFO]  Registered 0 entrypoints.
2023-08-16T13:49:42.500045        [INFO]  Building call graph.
java.lang.IllegalStateException: Could not create a entrypoint callsites: 1. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/BackOrderMgr
2. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/CatalogMgr
3. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/CustomerMgr
4. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/EMailMessage
5. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/MailerAppException
6. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/MailerBean
7. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/NoSupplierException
8. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/PopulateDBBean
9. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/ResetDBBean
10. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/ShoppingCartBean
11. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/ShoppingCartContent
12. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/bean/SuppliersBean
13. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/jpa/BackOrder
14. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/jpa/Customer
15. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/jpa/Inventory
16. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/jpa/Order
17. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/jpa/OrderItem
18. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/jpa/OrderItem$PK
19. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/jpa/OrderKey
20. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/jpa/Supplier
21. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/utils/ListProperties
22. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/utils/Util
23. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/AccountBean
24. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/AccountServlet
25. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/AdminServlet
26. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/BackOrderItem
27. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/HelpBean
28. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/ImageServlet
29. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/LoginInfo
30. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/MailAction
31. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/OrderInfo
32. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/Populate
33. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/ProductBean
34. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/ShoppingBean
35. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/ShoppingItem
36. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/ValidatePasswords
37. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$InvalidClassFile : LWEB-INF/classes/com/ibm/websphere/samples/pbw/war/ValidatorUtils
38. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/BasicImageReader
39. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/BasicImageReader$1
40. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/BasicImageReader$2
41. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageBufferCache
42. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageBufferCache$1
43. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageBufferCache$2
44. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageBufferCache$BufferReference
45. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageHeader
46. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageLocation
47. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader
48. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$Directory
49. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$LinkNode
50. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$Node
51. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$Resource
52. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$SharedImageReader
53. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReader$SharedImageReader$LocationVisitor
54. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReaderFactory
55. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageReaderFactory$1
56. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageStream
57. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageStrings
58. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/ImageStringsReader
59. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/NativeImageBuffer
60. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/NativeImageBuffer$1
61. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/CompressIndexes
62. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/CompressedResourceHeader
63. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/Decompressor
64. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ResourceDecompressor
65. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ResourceDecompressor$StringsProvider
66. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ResourceDecompressorFactory
67. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ResourceDecompressorRepository
68. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/SignatureParser
69. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/SignatureParser$ParseResult
70. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/StringSharingDecompressor
71. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/StringSharingDecompressorFactory
72. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ZipDecompressor
73. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jimage/decompressor/ZipDecompressorFactory
74. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/ExplodedImage
75. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/ExplodedImage$PathNode
76. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtDirectoryStream
77. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtDirectoryStream$1
78. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileAttributeView
79. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileAttributeView$1
80. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileAttributeView$AttrID
81. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileAttributes
82. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileStore
83. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystem
84. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystem$1
85. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystemProvider
86. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystemProvider$1
87. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtFileSystemProvider$JrtFsLoader
88. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtPath
89. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtPath$1
90. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtPath$2
91. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/JrtUtils
92. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/SystemImage
93. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/SystemImage$1
94. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Ljdk/internal/jrtfs/SystemImage$2

        at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:238)
        at org.konveyor.dgi.CodeAnalyzer.run(CodeAnalyzer.java:134)
        at org.konveyor.dgi.CodeAnalyzer.main(CodeAnalyzer.java:94)
```

**Comment by fabio-franco** [comment]
Fixed by https://github.com/konveyor/dgi-code-analyzer/issues/14
